name: "Build docs"
on:
    push:
      branches: master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
    
      - name: Build integration tests runner
        run: nix build .#documentation
