name: "Build docs"
on:
    push:
      branches: master
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
    
      - name: Build integration tests runner
        run: nix build .#documentation
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: docs
          path: result/_site/
          overwrite: true
          if-no-files-found: error
