name: "Integration testing"
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build integration tests runner
        run: nix build .#integration-testing
  
      - name: Run integration testing
        run: nix run .#integration-testing
