name: "Validate PR"

on:
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

  build-docs:
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: Build documntation
        run: nix build .#documentation

  tests:
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: Build integration tests runner
        run: nix build .#integration-testing

      - name: Run integration testing
        run: nix run .#integration-testing
