name: "Docs"

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

  build-docs:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Build documntation
        run: nix build .#documentation

      - name: Upload a Build Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: result/_site/

  tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build integration tests runner
        run: nix build .#integration-testing

      - name: Run integration testing
        run: nix run .#integration-testing

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
